import { Course, Lesson, User } from "@/lib/types";

// Mock data
const mockUsers: User[] = [
  {
    id: "2",
    email: "instructor@example.com",
    name: "Jane Instructor",
    role: "instructor",
    createdAt: new Date(),
  },
];

const mockCourses: Course[] = [
  {
    id: "1",
    title: "The Complete Web Development Bootcamp 2025",
    description:
      "Learn web development from scratch with HTML, CSS, JavaScript, Node.js, and more.",
    price: 84.99,
    thumbnail: "/altumcode-dC6Pb2JdAqs-unsplash.jpg",
    instructorId: "2",
    instructor: mockUsers[0],
    category: "Development",
    lessons: [
      {
        id: "1-1",
        title: "Course Introduction",
        videoUrl: "https://example.com/video1.mp4",
        duration: 300,
        order: 1,
      },
      {
        id: "1-2",
        title: "HTML Fundamentals",
        videoUrl: "https://example.com/video2.mp4",
        duration: 600,
        order: 2,
      },
      {
        id: "1-3",
        title: "CSS Basics",
        videoUrl: "https://example.com/video3.mp4",
        duration: 450,
        order: 3,
      },
    ],
    rating: 4.8,
    reviewsCount: 245000,
    studentsCount: 890000,
    duration: 65,
    level: "beginner",
    createdAt: new Date(),
    published: true,
  },
  {
    id: "2",
    title: "Machine Learning A-Z: AI, Python & R",
    description:
      "Complete machine learning course with Python and R programming.",
    price: 79.99,
    thumbnail: "/brooke-cagle-g1Kr4Ozfoac-unsplash.jpg",
    instructorId: "2",
    instructor: mockUsers[0],
    category: "Data Science",
    lessons: [
      {
        id: "2-1",
        title: "ML Introduction",
        videoUrl: "https://example.com/video4.mp4",
        duration: 400,
        order: 1,
      },
      {
        id: "2-2",
        title: "Python for ML",
        videoUrl: "https://example.com/video5.mp4",
        duration: 800,
        order: 2,
      },
    ],
    rating: 4.7,
    reviewsCount: 178000,
    studentsCount: 650000,
    duration: 44,
    level: "intermediate",
    createdAt: new Date(),
    published: true,
  },
  {
    id: "3",
    title: "iOS & Swift - The Complete iOS App Development",
    description: "Build iOS apps from scratch with Swift programming language.",
    price: 89.99,
    thumbnail: "/boliviainteligente-aP61AhDoAm0-unsplash.jpg",
    instructorId: "2",
    instructor: mockUsers[0],
    category: "Development",
    lessons: [
      {
        id: "3-1",
        title: "Swift Basics",
        videoUrl: "https://example.com/video6.mp4",
        duration: 500,
        order: 1,
      },
      {
        id: "3-2",
        title: "iOS UI Design",
        videoUrl: "https://example.com/video7.mp4",
        duration: 600,
        order: 2,
      },
    ],
    rating: 4.8,
    reviewsCount: 89000,
    studentsCount: 320000,
    duration: 60,
    level: "intermediate",
    createdAt: new Date(),
    published: true,
  },
  {
    id: "4",
    title: "React - The Complete Guide (incl Hooks, React Router, Redux)",
    description:
      "Dive in and learn React.js from scratch! Learn Reactjs, Hooks, and Redux.",
    price: 74.99,
    thumbnail: "/campaign-creators-gMsnXqILjp4-unsplash.jpg",
    instructorId: "2",
    instructor: mockUsers[0],
    category: "Development",
    lessons: [
      {
        id: "4-1",
        title: "Getting Started",
        videoUrl: "https://example.com/video8.mp4",
        duration: 350,
        order: 1,
      },
      {
        id: "4-2",
        title: "JSX & Components",
        videoUrl: "https://example.com/video9.mp4",
        duration: 550,
        order: 2,
      },
    ],
    rating: 4.7,
    reviewsCount: 156000,
    studentsCount: 580000,
    duration: 48,
    level: "intermediate",
    createdAt: new Date(),
    published: true,
  },
  {
    id: "5",
    title: "The Complete Digital Marketing Course - 12 Courses in 1",
    description:
      "Master digital marketing with this comprehensive course covering all aspects.",
    price: 69.99,
    thumbnail: "/daniel-korpai-mxPiMiz7KCo-unsplash.jpg",
    instructorId: "2",
    instructor: mockUsers[0],
    category: "Marketing",
    lessons: [
      {
        id: "5-1",
        title: "Digital Marketing Overview",
        videoUrl: "https://example.com/video10.mp4",
        duration: 400,
        order: 1,
      },
      {
        id: "5-2",
        title: "SEO Fundamentals",
        videoUrl: "https://example.com/video11.mp4",
        duration: 700,
        order: 2,
      },
    ],
    rating: 4.6,
    reviewsCount: 92000,
    studentsCount: 340000,
    duration: 52,
    level: "beginner",
    createdAt: new Date(),
    published: true,
  },
  {
    id: "6",
    title: "UX/UI Design - Adobe XD UI/UX Design Course",
    description:
      "Learn UI/UX design with Adobe XD. Create stunning user interfaces.",
    price: 59.99,
    thumbnail: "/erik-mclean-2Wv9VnwzeeI-unsplash.jpg",
    instructorId: "2",
    instructor: mockUsers[0],
    category: "Design",
    lessons: [
      {
        id: "6-1",
        title: "Design Principles",
        videoUrl: "https://example.com/video12.mp4",
        duration: 450,
        order: 1,
      },
      {
        id: "6-2",
        title: "Adobe XD Basics",
        videoUrl: "https://example.com/video13.mp4",
        duration: 600,
        order: 2,
      },
    ],
    rating: 4.5,
    reviewsCount: 67000,
    studentsCount: 240000,
    duration: 38,
    level: "beginner",
    createdAt: new Date(),
    published: true,
  },
  {
    id: "7",
    title: "Python for Data Science and Machine Learning Bootcamp",
    description:
      "Learn to use NumPy, Pandas, Seaborn, Matplotlib, Plotly, Scikit-Learn.",
    price: 94.99,
    thumbnail: "/maac-india-Yk3FgdgwjlE-unsplash.jpg",
    instructorId: "2",
    instructor: mockUsers[0],
    category: "Data Science",
    lessons: [
      {
        id: "7-1",
        title: "Python Basics",
        videoUrl: "https://example.com/video14.mp4",
        duration: 500,
        order: 1,
      },
      {
        id: "7-2",
        title: "Data Analysis with Pandas",
        videoUrl: "https://example.com/video15.mp4",
        duration: 800,
        order: 2,
      },
    ],
    rating: 4.8,
    reviewsCount: 134000,
    studentsCount: 480000,
    duration: 58,
    level: "intermediate",
    createdAt: new Date(),
    published: true,
  },
  {
    id: "8",
    title: "The Complete Business Analysis Professional Certification",
    description:
      "Become a certified business analyst with this comprehensive course.",
    price: 49.99,
    thumbnail: "/alexander-shatov-mr4JG4SYOF8-unsplash.jpg",
    instructorId: "2",
    instructor: mockUsers[0],
    category: "Business",
    lessons: [
      {
        id: "8-1",
        title: "Business Analysis Fundamentals",
        videoUrl: "https://example.com/video16.mp4",
        duration: 400,
        order: 1,
      },
      {
        id: "8-2",
        title: "Requirements Gathering",
        videoUrl: "https://example.com/video17.mp4",
        duration: 550,
        order: 2,
      },
    ],
    rating: 4.4,
    reviewsCount: 45000,
    studentsCount: 160000,
    duration: 42,
    level: "beginner",
    createdAt: new Date(),
    published: true,
  },
  {
    id: "9",
    title: "Angular - The Complete Guide (2025 Edition)",
    description:
      "Master Angular (formerly Angular 2) and build awesome, reactive web apps.",
    price: 79.99,
    thumbnail: "/brecht-corbeel-QUwM2LDVs3A-unsplash.jpg",
    instructorId: "2",
    instructor: mockUsers[0],
    category: "Development",
    lessons: [
      {
        id: "9-1",
        title: "Angular Basics",
        videoUrl: "https://example.com/video18.mp4",
        duration: 450,
        order: 1,
      },
      {
        id: "9-2",
        title: "Components & Directives",
        videoUrl: "https://example.com/video19.mp4",
        duration: 650,
        order: 2,
      },
    ],
    rating: 4.6,
    reviewsCount: 112000,
    studentsCount: 410000,
    duration: 46,
    level: "intermediate",
    createdAt: new Date(),
    published: true,
  },
  {
    id: "10",
    title: "The Complete Cyber Security Course: Hackers Exposed!",
    description:
      "Learn ethical hacking, penetration testing, and cyber security.",
    price: 99.99,
    thumbnail: "/altumcode-dC6Pb2JdAqs-unsplash.jpg",
    instructorId: "2",
    instructor: mockUsers[0],
    category: "IT & Software",
    lessons: [
      {
        id: "10-1",
        title: "Cyber Security Basics",
        videoUrl: "https://example.com/video20.mp4",
        duration: 500,
        order: 1,
      },
      {
        id: "10-2",
        title: "Network Security",
        videoUrl: "https://example.com/video21.mp4",
        duration: 700,
        order: 2,
      },
    ],
    rating: 4.7,
    reviewsCount: 78000,
    studentsCount: 280000,
    duration: 55,
    level: "intermediate",
    createdAt: new Date(),
    published: true,
  },
  {
    id: "11",
    title: "Photography Masterclass: A Complete Guide to Photography",
    description: "Learn photography from basics to advanced techniques.",
    price: 39.99,
    thumbnail: "/brooke-cagle-g1Kr4Ozfoac-unsplash.jpg",
    instructorId: "2",
    instructor: mockUsers[0],
    category: "Photography",
    lessons: [
      {
        id: "11-1",
        title: "Camera Basics",
        videoUrl: "https://example.com/video22.mp4",
        duration: 350,
        order: 1,
      },
      {
        id: "11-2",
        title: "Composition & Lighting",
        videoUrl: "https://example.com/video23.mp4",
        duration: 600,
        order: 2,
      },
    ],
    rating: 4.5,
    reviewsCount: 56000,
    studentsCount: 200000,
    duration: 35,
    level: "beginner",
    createdAt: new Date(),
    published: true,
  },
  {
    id: "12",
    title: "The Complete Financial Analyst Course 2025",
    description:
      "Master financial analysis, modeling, and valuation techniques.",
    price: 89.99,
    thumbnail: "/boliviainteligente-aP61AhDoAm0-unsplash.jpg",
    instructorId: "2",
    instructor: mockUsers[0],
    category: "Business",
    lessons: [
      {
        id: "12-1",
        title: "Financial Statements",
        videoUrl: "https://example.com/video24.mp4",
        duration: 550,
        order: 1,
      },
      {
        id: "12-2",
        title: "Financial Modeling",
        videoUrl: "https://example.com/video25.mp4",
        duration: 750,
        order: 2,
      },
    ],
    rating: 4.6,
    reviewsCount: 67000,
    studentsCount: 240000,
    duration: 50,
    level: "intermediate",
    createdAt: new Date(),
    published: true,
  },
  {
    id: "13",
    title: "Node.js, Express, MongoDB & More: The Complete Bootcamp",
    description:
      "Build real world backend applications with Node.js, Express, and MongoDB.",
    price: 64.99,
    thumbnail: "/campaign-creators-gMsnXqILjp4-unsplash.jpg",
    instructorId: "2",
    instructor: mockUsers[0],
    category: "Development",
    lessons: [
      {
        id: "13-1",
        title: "Node.js Fundamentals",
        videoUrl: "https://example.com/video26.mp4",
        duration: 450,
        order: 1,
      },
      {
        id: "13-2",
        title: "Express.js Basics",
        videoUrl: "https://example.com/video27.mp4",
        duration: 600,
        order: 2,
      },
    ],
    rating: 4.7,
    reviewsCount: 98000,
    studentsCount: 350000,
    duration: 42,
    level: "intermediate",
    createdAt: new Date(),
    published: true,
  },
  {
    id: "14",
    title: "The Complete Graphic Design Theory for Beginners Course",
    description:
      "Learn the fundamentals of graphic design and visual communication.",
    price: 44.99,
    thumbnail: "/daniel-korpai-mxPiMiz7KCo-unsplash.jpg",
    instructorId: "2",
    instructor: mockUsers[0],
    category: "Design",
    lessons: [
      {
        id: "14-1",
        title: "Design Theory",
        videoUrl: "https://example.com/video28.mp4",
        duration: 400,
        order: 1,
      },
      {
        id: "14-2",
        title: "Color Theory",
        videoUrl: "https://example.com/video29.mp4",
        duration: 500,
        order: 2,
      },
    ],
    rating: 4.4,
    reviewsCount: 34000,
    studentsCount: 120000,
    duration: 28,
    level: "beginner",
    createdAt: new Date(),
    published: true,
  },
  {
    id: "15",
    title: "Advanced JavaScript Concepts",
    description:
      "Master advanced JavaScript concepts including closures, prototypes, and async programming.",
    price: 54.99,
    thumbnail: "/erik-mclean-2Wv9VnwzeeI-unsplash.jpg",
    instructorId: "2",
    instructor: mockUsers[0],
    category: "Development",
    lessons: [
      {
        id: "15-1",
        title: "Advanced Functions",
        videoUrl: "https://example.com/video30.mp4",
        duration: 500,
        order: 1,
      },
      {
        id: "15-2",
        title: "Async Programming",
        videoUrl: "https://example.com/video31.mp4",
        duration: 650,
        order: 2,
      },
    ],
    rating: 4.6,
    reviewsCount: 78000,
    studentsCount: 280000,
    duration: 36,
    level: "advanced",
    createdAt: new Date(),
    published: true,
  },
  {
    id: "16",
    title: "Social Media Marketing Mastery 2025",
    description: "Master social media marketing across all major platforms.",
    price: 34.99,
    thumbnail: "/maac-india-Yk3FgdgwjlE-unsplash.jpg",
    instructorId: "2",
    instructor: mockUsers[0],
    category: "Marketing",
    lessons: [
      {
        id: "16-1",
        title: "Social Media Strategy",
        videoUrl: "https://example.com/video32.mp4",
        duration: 350,
        order: 1,
      },
      {
        id: "16-2",
        title: "Content Creation",
        videoUrl: "https://example.com/video33.mp4",
        duration: 450,
        order: 2,
      },
    ],
    rating: 4.3,
    reviewsCount: 45000,
    studentsCount: 160000,
    duration: 25,
    level: "beginner",
    createdAt: new Date(),
    published: true,
  },
  {
    id: "17",
    title: "Deep Learning A-Z: Neural Networks, AI & Python",
    description:
      "Learn to create deep learning algorithms in Python using TensorFlow and Keras.",
    price: 109.99,
    thumbnail: "/alexander-shatov-mr4JG4SYOF8-unsplash.jpg",
    instructorId: "2",
    instructor: mockUsers[0],
    category: "Data Science",
    lessons: [
      {
        id: "17-1",
        title: "Neural Networks Basics",
        videoUrl: "https://example.com/video34.mp4",
        duration: 600,
        order: 1,
      },
      {
        id: "17-2",
        title: "TensorFlow Fundamentals",
        videoUrl: "https://example.com/video35.mp4",
        duration: 800,
        order: 2,
      },
    ],
    rating: 4.8,
    reviewsCount: 56000,
    studentsCount: 200000,
    duration: 62,
    level: "advanced",
    createdAt: new Date(),
    published: true,
  },
  {
    id: "18",
    title: "The Complete Public Speaking Masterclass for Beginners",
    description:
      "Overcome your fear of public speaking and become a confident presenter.",
    price: 29.99,
    thumbnail: "/brecht-corbeel-QUwM2LDVs3A-unsplash.jpg",
    instructorId: "2",
    instructor: mockUsers[0],
    category: "Personal Development",
    lessons: [
      {
        id: "18-1",
        title: "Overcoming Fear",
        videoUrl: "https://example.com/video36.mp4",
        duration: 300,
        order: 1,
      },
      {
        id: "18-2",
        title: "Presentation Skills",
        videoUrl: "https://example.com/video37.mp4",
        duration: 400,
        order: 2,
      },
    ],
    rating: 4.5,
    reviewsCount: 23000,
    studentsCount: 82000,
    duration: 18,
    level: "beginner",
    createdAt: new Date(),
    published: true,
  },
  {
    id: "19",
    title: "Docker & Kubernetes: The Complete Guide",
    description: "Master Docker and Kubernetes for container orchestration.",
    price: 79.99,
    thumbnail: "/altumcode-dC6Pb2JdAqs-unsplash.jpg",
    instructorId: "2",
    instructor: mockUsers[0],
    category: "IT & Software",
    lessons: [
      {
        id: "19-1",
        title: "Docker Fundamentals",
        videoUrl: "https://example.com/video38.mp4",
        duration: 550,
        order: 1,
      },
      {
        id: "19-2",
        title: "Kubernetes Basics",
        videoUrl: "https://example.com/video39.mp4",
        duration: 700,
        order: 2,
      },
    ],
    rating: 4.7,
    reviewsCount: 45000,
    studentsCount: 160000,
    duration: 45,
    level: "intermediate",
    createdAt: new Date(),
    published: true,
  },
  {
    id: "20",
    title: "Music Production Masterclass: The Complete Guide",
    description:
      "Learn music production from mixing to mastering using professional tools.",
    price: 69.99,
    thumbnail: "/brooke-cagle-g1Kr4Ozfoac-unsplash.jpg",
    instructorId: "2",
    instructor: mockUsers[0],
    category: "Music",
    lessons: [
      {
        id: "20-1",
        title: "Music Theory Basics",
        videoUrl: "https://example.com/video40.mp4",
        duration: 400,
        order: 1,
      },
      {
        id: "20-2",
        title: "Recording Techniques",
        videoUrl: "https://example.com/video41.mp4",
        duration: 600,
        order: 2,
      },
    ],
    rating: 4.6,
    reviewsCount: 34000,
    studentsCount: 120000,
    duration: 40,
    level: "intermediate",
    createdAt: new Date(),
    published: true,
  },
];

export function getAllCourses(): Course[] {
  return mockCourses;
}

export function getCourseById(id: string): Course | null {
  return mockCourses.find((course) => course.id === id) || null;
}

export function getCoursesByCategory(category: string): Course[] {
  return mockCourses.filter(
    (course) => course.category.toLowerCase() === category.toLowerCase()
  );
}

export function getCoursesByInstructor(instructorId: string): Course[] {
  return mockCourses.filter((course) => course.instructorId === instructorId);
}

export function searchCourses(query: string): Course[] {
  const lowerQuery = query.toLowerCase();
  return mockCourses.filter(
    (course) =>
      course.title.toLowerCase().includes(lowerQuery) ||
      course.description.toLowerCase().includes(lowerQuery) ||
      course.category.toLowerCase().includes(lowerQuery)
  );
}
